#!/usr/bin/env python3
"""
Generate the benchmark kernels as raw 32-bit x86 machine code.

Each kernel is an endless loop. The harness counts guest instructions retired
per second, so the loop never has to terminate.

The point of the set is contrast, not absolute speed. "alu" touches no data at
all, so it measures pure interpreter dispatch. "seq" walks memory one cache
line at a time, "stride" jumps 4160 bytes so it defeats both the cache and the
TLB, and "store" does the same but dirties the line. On a machine whose guest
RAM sits behind a cache, alu and stride should land within a small factor of
each other. On the RP2350, where guest RAM is QSPI PSRAM with no data cache,
stride should collapse. That gap is the whole question.

Every encoding is disassembled back with capstone before being written out, so
a hand-encoding slip cannot silently become a bogus measurement.
"""

import sys

DATA_BASE = 0x100000          # guest data window starts 1 MB in
MASK_REG_VALUE = 0x003FFFC0   # 4 MB window, 64-byte aligned; fits 8 MB of RAM


def imm32(v):
    return [v & 0xFF, (v >> 8) & 0xFF, (v >> 16) & 0xFF, (v >> 24) & 0xFF]


# Each entry: (mnemonic for the record, bytes)
def kernel_alu():
    """Register-only ALU. No data memory touched; instruction fetch only."""
    body = []
    for _ in range(2):
        body += [0x01, 0xD8]        # add eax, ebx
        body += [0x31, 0xD1]        # xor ecx, edx
        body += [0x29, 0xFE]        # sub esi, edi
        body += [0x45]              # inc ebp
    return body


def kernel_seq():
    """One 32-bit load per cache line, walking forward."""
    body = []
    body += [0x8B, 0x86] + imm32(DATA_BASE)   # mov eax, [esi + DATA_BASE]
    body += [0x83, 0xC6, 0x40]                # add esi, 64
    body += [0x21, 0xDE]                      # and esi, ebx
    return body


def kernel_stride():
    """One load per 4160 bytes: a new page almost every time."""
    body = []
    body += [0x8B, 0x86] + imm32(DATA_BASE)   # mov eax, [esi + DATA_BASE]
    body += [0x81, 0xC6] + imm32(0x1040)      # add esi, 0x1040
    body += [0x21, 0xDE]                      # and esi, ebx
    return body


def kernel_store():
    """Same stride, but writing. Exercises the store path and dirty traffic."""
    body = []
    body += [0x89, 0x86] + imm32(DATA_BASE)   # mov [esi + DATA_BASE], eax
    body += [0x81, 0xC6] + imm32(0x1040)      # add esi, 0x1040
    body += [0x21, 0xDE]                      # and esi, ebx
    return body


def kernel_mixed():
    """Stack traffic plus a load: closer in shape to real guest code."""
    body = []
    body += [0x55]                            # push ebp
    body += [0x8B, 0x86] + imm32(DATA_BASE)   # mov eax, [esi + DATA_BASE]
    body += [0x5D]                            # pop ebp
    body += [0x83, 0xC6, 0x40]                # add esi, 64
    body += [0x21, 0xDE]                      # and esi, ebx
    return body


KERNELS = [
    ("alu",    kernel_alu,    "register-only ALU, no data memory"),
    ("seq",    kernel_seq,    "32-bit load, +64 B per step (streaming)"),
    ("stride", kernel_stride, "32-bit load, +4160 B per step (cache/TLB hostile)"),
    ("store",  kernel_store,  "32-bit store, +4160 B per step"),
    ("mixed",  kernel_mixed,  "push/pop + load, +64 B per step"),
]


def close_loop(body):
    """Append a short jmp back to offset 0."""
    rel = -(len(body) + 2)
    assert -128 <= rel <= 127, "loop body too long for a short jmp"
    return body + [0xEB, rel & 0xFF]


def verify(name, code):
    try:
        from capstone import Cs, CS_ARCH_X86, CS_MODE_32
    except ImportError:
        print("  (capstone unavailable - encoding NOT verified)", file=sys.stderr)
        return None
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    listing, count, consumed = [], 0, 0
    for ins in md.disasm(bytes(code), 0):
        listing.append("    %-4d %-20s %s" % (ins.address, ins.mnemonic, ins.op_str))
        count += 1
        consumed += ins.size
    if consumed != len(code):
        raise SystemExit("%s: capstone consumed %d of %d bytes - bad encoding"
                         % (name, consumed, len(code)))
    return count, listing


def main():
    out = []
    out.append("/* Generated by gen_payload.py - do not edit. */")
    out.append("")
    out.append("typedef struct {")
    out.append("\tconst char *name;")
    out.append("\tconst char *desc;")
    out.append("\tconst unsigned char *code;")
    out.append("\tunsigned len;")
    out.append("\tunsigned insns_per_iter;")
    out.append("} kernel_t;")
    out.append("")
    out.append("#define BENCH_DATA_BASE 0x%08Xu" % DATA_BASE)
    out.append("#define BENCH_MASK      0x%08Xu" % MASK_REG_VALUE)
    out.append("")

    entries = []
    for name, fn, desc in KERNELS:
        code = close_loop(fn())
        res = verify(name, code)
        n = res[0] if res else 0
        print("%-8s %2d bytes, %d instructions per iteration" % (name, len(code), n))
        if res:
            for line in res[1]:
                print(line)
        body = ", ".join("0x%02X" % b for b in code)
        out.append("static const unsigned char k_%s[] = { %s };" % (name, body))
        entries.append((name, desc, n))
    out.append("")
    out.append("static const kernel_t kernels[] = {")
    for name, desc, n in entries:
        out.append('\t{ "%s", "%s", k_%s, sizeof(k_%s), %d },'
                   % (name, desc, name, name, n))
    out.append("};")
    out.append("#define NKERNELS (sizeof(kernels)/sizeof(kernels[0]))")
    out.append("")

    with open("payload.inc", "w") as f:
        f.write("\n".join(out))
    print("\npayload.inc written (%d kernels)" % len(entries))


if __name__ == "__main__":
    main()
